name: NASA Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: cd client && yarn run build
